language: php

sudo: false

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0a100612ee5327ce066f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
    - php: hhvm

branches:
  only:
    - "master"
    - "2.5"
    - "3.0"

cache:
  directories:
    - vendor
    - node_modules

before_install:
  - nvm install 0.12
  - nvm use 0.12
  - npm config set spin false

install:
  - npm install karma karma-jasmine karma-phantomjs-launcher jasmine-core
  #- composer install --no-progress
  - composer update --prefer-lowest

before_script:
  - echo 'date.timezone = "America/Los_Angeles"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mkdir -p build/logs

script:
  #- php -i | grep timezone
  - phpunit -c configs/phpunit.xml.dist
  - npm test

after_script:
  - php vendor/bin/coveralls
