language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm

branches:
  only:
    - "master"
    - "3.0"
    - "2.5"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - vendor
    - node_modules

addons:
    code_climate:
        repo_token: 2f9d341839519e41ab143a4266d37887674d9ed0e5304929d8622125314a17df

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0a100612ee5327ce066f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

before_install:
  - nvm install 0.10
  - nvm use 0.10
  - npm config set spin false
  - composer selfupdate

install:
  - composer install --no-progress --no-interaction --prefer-dist
  - npm install --no-progress --production

before_script:
  - echo 'date.timezone = "America/Los_Angeles"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mkdir -p build/logs

script:
  - composer run test
  - npm run test

after_script:
  - php ./vendor/bin/coveralls
