language: php

sudo: false

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0a100612ee5327ce066f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

php:
  - 5.4
  - 5.5
  - 5.6
<<<<<<< HEAD
  - 7.0
=======
  - 7
>>>>>>> master
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
<<<<<<< HEAD
    - php: 7.0
=======
    - php: 7
>>>>>>> master
    - php: hhvm

branches:
  only:
    - "master"
<<<<<<< HEAD
=======
    - "2.5"
>>>>>>> master
    - "3.0"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - vendor
    - node_modules

before_install:
  - nvm install 0.10
  - nvm use 0.10
  - npm config set spin false
  - composer selfupdate

install:
  - composer install --no-progress --no-interaction --prefer-dist
  - npm install --no-progress --production

before_script:
  - echo 'date.timezone = "America/Los_Angeles"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mkdir -p build/logs

script:
  - phpunit -c configs/phpunit.xml.dist
  - npm test

after_script:
  - php vendor/bin/coveralls
